services:
  grafana:
      image: grafana/grafana:latest
      container_name: grafana
      ports:
        - "3000:3000"
      environment:
        GF_SECURITY_ADMIN_USER: admin
        GF_SECURITY_ADMIN_PASSWORD: admin
        # Install the official ClickHouse plugin
        GF_INSTALL_PLUGINS: grafana-clickhouse-datasource
      volumes:
        - ./grafana/provisioning:/etc/grafana/provisioning
        - grafana_data:/var/lib/grafana
      depends_on:
        - clickhouse

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports: ["5432:5432"] 
    environment:
      POSTGRES_DB: ad_oltp
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d   # optional: init SQL

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports: ["8123:8123", "9000:9000"]
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=mysecret
      - CLICKHOUSE_DB=ctv
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ulimits: { nofile: { soft: 262144, hard: 262144 } }
    volumes:
      - ch_data:/var/lib/clickhouse
      - ch_logs:/var/log/clickhouse-server
    healthcheck:
      # Considered "healthy" only when auth works and a trivial query succeeds
      test: ["CMD-SHELL", "clickhouse-client -u \"$${CLICKHOUSE_USER}\" --password \"$${CLICKHOUSE_PASSWORD}\" --query 'SELECT 1' >/dev/null 2>&1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s

  clickhouse-init:
    image: clickhouse/clickhouse-server:latest
    depends_on:
      clickhouse: { condition: service_healthy }
    environment:
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=mysecret
      - CLICKHOUSE_DB=ctv
      - SQL_DIR=/clickhouse/init
    volumes:
      - ./scripts/ch-init.sh:/init/ch-init.sh
      - ./clickhouse/init:/clickhouse/init:ro
    entrypoint: ["/bin/bash","-lc","chmod +x /init/ch-init.sh && /init/ch-init.sh"]
    restart: no

  kafka-ui:
    image: kafbat/kafka-ui:main
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    depends_on:
      - kafka

  kafka:
    image: apache/kafka-native
    ports:
      - "9092:9092"
    environment:
      # Configure listeners for both docker and host communication
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT

      # Settings required for KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091

      # Listener to use for broker-to-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      # Required for a single node cluster
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  grafana_data:
  pg_data:
  ch_data:
  ch_logs: