apiVersion: 1
datasources:
  - name: Postgres (OLTP)
    type: postgres
    access: proxy
    isDefault: false
    url: postgres:5432
    user: app
    database: ad_oltp
    jsonData:
      postgresVersion: 1600   # 16.x
      sslmode: disable
      timeInterval: 1m
      timescaledb: false
    secureJsonData:
      password: app
